name: Dependency Update

"on":
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Run neophile
        uses: lsst-sqre/run-neophile@v1
        with:
          python-version: "3.11"
          mode: pr
          types: pre-commit
          app-id: ${{ secrets.NEOPHILE_APP_ID }}
          app-secret: ${{ secrets.NEOPHILE_PRIVATE_KEY }}

      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Periodic dependency update for {repo} failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}
